periodics:
  - name: periodic-configs-autobump
    # Run at minute 5 past every hour from 18 through 23 on every Monday (At UTC+8 timezone).
    cron: "05 10-15 * * 1"
    decorate: true
    extra_refs:
      # Check out the repo containing the config and deployment files for your Prow instance.
      - org: ti-community-infra
        repo: configs
        base_ref: main
    spec:
      containers:
        - image: gcr.io/k8s-prow/autobump:v20210401-1e772aaa42
          command:
            - /autobump.sh
          args:
            - /etc/github/token
            # Make the bot name and email match the user data of the provided token's user.
            - "ti-chi-bot"
            - ti-community-prow-bot@tidb.io
          volumeMounts:
            - name: github-token
              mountPath: /etc/github
              readOnly: true
          env:
            # autobump.sh args
            # GitHub org containing the repo where the Prow config and component files live.
            - name: GH_ORG
              value: ti-community-infra
            # GitHub repo where the Prow config and component deployment files live.
            - name: GH_REPO
              value: configs
            # Repo relative path of the `plank` component k8s deployment file.
            - name: PROW_CONTROLLER_MANAGER_FILE
              value: prow/cluster/prow_controller_manager_deployment.yaml
            # bump.sh args
            # Directory (or comma-delimited list of directories) containing k8s deployment YAMLs for Prow components.
            - name: COMPONENT_FILE_DIR
              value: prow/cluster
            # Repo relative path of the core Prow config file (config.yaml).
            - name: CONFIG_PATH
              value: prow/config/config.yaml
            # Repo relative path of the ProwJob config file or directory.
            # Omit this if ProwJobs are only defined in config.yaml (or are not configured at all).
            - name: JOB_CONFIG_PATH
              value: prow/jobs
            # PR title prefix.
            - name: AUTOBUMP_TITLE_PREFIX
              value: "build: "
      volumes:
        - name: github-token
          secret:
            # Secret containing a GitHub user access token with `repo` scope for creating PRs.
            secretName: github-token
  - name: periodic-configs-label-sync
    # Run at every hour.
    cron: "0 * * * *"
    decorate: true
    extra_refs:
      # Check out the repo containing the config and deployment files for your Prow instance.
      - org: ti-community-infra
        repo: configs
        base_ref: main
    spec:
      containers:
        - image: gcr.io/k8s-prow/label_sync:v20210521-0713522bd8
          command:
            - /app/label_sync/app.binary
          args:
            - --config=prow/config/labels.yaml
            - --confirm=true
            - --only=ti-community-infra/tichi,ti-community-infra/configs,ti-community-infra/ti-community-bot,ti-community-infra/ti-challenge-bot,ti-community-infra/rfcs,ti-community-infra/devstats,ti-community-infra/devstats-dev-guide,pingcap/community,pingcap/docs,pingcap/docs-cn,pingcap/docs-dm,pingcap/docs-tidb-operator,pingcap/ticdc,tikv/community,tikv/pd,chaos-mesh/website,chaos-mesh/website-zh
            - --token=/etc/github/token
          volumeMounts:
            - name: github-token
              mountPath: /etc/github
              readOnly: true
      volumes:
        - name: github-token
          secret:
            secretName: github-token
